
package Presentacion.Command;

public enum ContextEnum {
	
	ALTACLIENTEJPA, BAJACLIENTEJPA, MODIFICARCLIENTEJPA, MOSTRARCLIENTEJPA, LISTARCLIENTESJPA,
	ALTADEPARTAMENTO, BAJADEPARTAMENTO, MODIFICARDEPARTAMENTO, MOSTRARDEPARTAMENTO, LISTARDEPARTAMENTOS,
	ALTAEMPLEADO, BAJAEMPLEADO, MODIFICAREMPLEADO, MOSTRAREMPLEADO, LISTAREMPLEADOS, LISTAREMPLEADOSCOMPLETO, LISTAREMPLEADOSPARCIAL, LISTAREMPLEADOSPORDEPARTAMENTO,
	ALTAPRODUCTO, BAJAPRODUCTO, MODIFICARPRODUCTO, MOSTRARPRODUCTO, LISTARPRODUCTOS, LISTARCOMIDAS, LISTARBEBIDAS, LISTARPRODUCTOSPORPROVEEDOR, LISTARPRODUCTOSPORVENTA, ANADIRPROVEEDOR, QUITARPROVEEDOR,
	ALTAPROVEEDOR, BAJAPROVEEDOR, MODIFICARPROVEEDOR, MOSTRARPROVEEDOR, LISTARPROVEEDORES, LISTARPROVEEDORESPORPRODUCTO,
	CERRARVENTA, MOSTRARVENTA, MOSTRARVENTAENDETALLE, LISTARVENTAS, LISTARVENTASPORCLIENTE, LISTARVENTASPORPRODUCTO, LISTARVENTASPOREMPLEADO, DEVOLVERVENTA
	
}