
package Presentacion.Command;


public enum EventEnum {
	
	// General
	BASEDEDATOS, CONCURRENCIA,
	ENTIDADREPETIDA, ENTIDADREPETIDAACTIVA, ENTIDADINACTIVA, ENTIDADINEXISTENTE,
	SINTAXIS, TIPOMODIFICADO,
	
	// Departamento
	DEPARTAMENTOINEXISTENTE, DEPARTAMENTOINACTIVO,
	
	// Producto
	PRODUCTOINEXISTENTE, PRODUCTOINACTIVO,
	ASOCIACIONEXISTENTE, ASOCIACIONINEXISTENTE,
	STOCKPRODUCTOVENDIDO,
	
	// Proveedor
	PROVEEDORINEXISTENTE, PROVEEDORINACTIVO,
	
	// Venta
	VENTAINEXISTENTE, 
	STOCKINSUFICIENTE, PRODUCTONOINCLUIDO,	
	
	// Cliente
	CLIENTEINEXISTENTE, CLIENTEINACTIVO,
	
	// Empleado
	EMPLEADOINEXISTENTE, EMPLEADOINACTIVO,
	
}